// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewPlasmaDonorsAPI.Data;

#nullable disable

namespace PlasmaDonorAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NewPlasmaDonorsAPI.Dto.CountDto", b =>
                {
                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.ToTable("countDto");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.Address", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("addressLine")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_line");

                    b.Property<string>("city")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city");

                    b.Property<string>("country")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country");

                    b.Property<string>("countryCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country_code");

                    b.Property<long?>("createdBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("fullAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_address");

                    b.Property<double?>("latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("postalCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("postal_code");

                    b.Property<string>("state")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("state");

                    b.Property<string>("stateCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("state_code");

                    b.Property<string>("status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<long?>("updatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("id");

                    b.HasIndex("createdBy");

                    b.HasIndex("updatedBy");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.Company", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.CompanyLocation", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("addressLine1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_line1");

                    b.Property<string>("addressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_line2");

                    b.Property<string>("city")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("city");

                    b.Property<string>("country")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country");

                    b.Property<string>("countryCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country_code");

                    b.Property<string>("fullAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("full_address");

                    b.Property<double?>("latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<double?>("longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone_number");

                    b.Property<string>("siteId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("site_id");

                    b.Property<string>("state")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("state");

                    b.Property<string>("stateCode")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("state_code");

                    b.Property<string>("status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.HasKey("id");

                    b.ToTable("company_locations", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.DonarInfluencerMap", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("influencedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("influenced_by");

                    b.Property<long>("profileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.HasKey("id");

                    b.HasIndex("influencedBy");

                    b.HasIndex("profileId");

                    b.ToTable("donar_influencer_map", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.DonorByOccupationResults", b =>
                {
                    b.Property<int>("Cnt")
                        .HasColumnType("int");

                    b.Property<string>("MdTitle")
                        .HasColumnType("longtext");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.ToTable("DonorByOccupationResults");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.DonorTimeSeriesResult", b =>
                {
                    b.Property<int>("Cont")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("DonorTimeSeriesResults");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.InfluencerTimeSeriesResult", b =>
                {
                    b.Property<int>("Cont")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.ToTable("InfluencerTimeSeriesResults");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.MasterData", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("createdBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("mdName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("md_name");

                    b.Property<string>("mdScore")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("md_score");

                    b.Property<string>("mdTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("md_title");

                    b.Property<string>("mdType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("md_type");

                    b.Property<string>("status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<long?>("updatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("id");

                    b.HasIndex("createdBy");

                    b.HasIndex("updatedBy");

                    b.ToTable("master_data", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.ProfileByStateResult", b =>
                {
                    b.Property<int>("Cnt")
                        .HasColumnType("int");

                    b.Property<string>("Str")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("ProfileByStateResults");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.ProfileMdMap", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("mdId")
                        .HasColumnType("bigint")
                        .HasColumnName("md_id");

                    b.Property<long?>("profileId")
                        .HasColumnType("bigint")
                        .HasColumnName("profile_id");

                    b.HasKey("id");

                    b.HasIndex("mdId");

                    b.HasIndex("profileId");

                    b.ToTable("profile_md_map", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.ProfileModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("HomeCenter")
                        .HasColumnType("bigint")
                        .HasColumnName("home_center");

                    b.Property<string>("InfluencedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("influenced_by");

                    b.Property<ulong?>("IsRelationshipActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_relationship_active");

                    b.Property<long?>("RelshipScoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("relship_score_id");

                    b.Property<string>("RelshipStatus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("relship_status");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<long?>("address_id")
                        .HasColumnType("bigint")
                        .HasColumnName("address_id");

                    b.Property<int?>("age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<long?>("createdBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dob");

                    b.Property<long?>("education_id")
                        .HasColumnType("bigint")
                        .HasColumnName("education_id");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("gender")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gender");

                    b.Property<long?>("homeCenterId")
                        .HasColumnType("bigint")
                        .HasColumnName("home_center_id");

                    b.Property<double>("infScore")
                        .HasColumnType("double");

                    b.Property<ulong?>("isDonor")
                        .HasColumnType("bit")
                        .HasColumnName("is_donor");

                    b.Property<ulong?>("isInfluencer")
                        .HasColumnType("bit")
                        .HasColumnName("is_influencer");

                    b.Property<long?>("language_id")
                        .HasColumnType("bigint")
                        .HasColumnName("language_id");

                    b.Property<string>("lastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<long?>("occupation_id")
                        .HasColumnType("bigint")
                        .HasColumnName("occupation_id");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone_number");

                    b.Property<long?>("race_id")
                        .HasColumnType("bigint")
                        .HasColumnName("race_id");

                    b.Property<long?>("relationship_id")
                        .HasColumnType("bigint")
                        .HasColumnName("relationship_id");

                    b.Property<long?>("relship_reason_id")
                        .HasColumnType("bigint")
                        .HasColumnName("relship_reason_id");

                    b.Property<string>("schoolAttended")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("school_attended");

                    b.Property<long?>("updatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.HasKey("id");

                    b.HasIndex("RelshipScoreId");

                    b.HasIndex("address_id");

                    b.HasIndex("createdBy");

                    b.HasIndex("education_id");

                    b.HasIndex("homeCenterId");

                    b.HasIndex("language_id");

                    b.HasIndex("occupation_id");

                    b.HasIndex("race_id");

                    b.HasIndex("relationship_id");

                    b.HasIndex("relship_reason_id");

                    b.HasIndex("updatedBy");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.Roles", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("role")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<string>("status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<string>("title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.TopInfluencerInfo", b =>
                {
                    b.Property<string>("AddressLine")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("InfScore")
                        .HasColumnType("double");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.UserModel", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long?>("company")
                        .HasMaxLength(255)
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<long?>("companyLocation")
                        .HasColumnType("bigint")
                        .HasColumnName("company_location_id");

                    b.Property<long?>("createdBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("createdOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<ulong?>("deleted")
                        .HasColumnType("bit")
                        .HasColumnName("deleted");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("firstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("lastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone_number");

                    b.Property<string>("role")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role");

                    b.Property<long?>("roleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<string>("roleType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role_type");

                    b.Property<string>("status")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status");

                    b.Property<long?>("updatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("updatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_on");

                    b.Property<string>("username")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.HasIndex("company");

                    b.HasIndex("companyLocation");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("roleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.Address", b =>
                {
                    b.HasOne("NewPlasmaDonorsAPI.Models.UserModel", "createdByUser")
                        .WithMany()
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKf2n4qm0147jxllli3xeutu6uv");

                    b.HasOne("NewPlasmaDonorsAPI.Models.UserModel", "updatedByUser")
                        .WithMany()
                        .HasForeignKey("updatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKhmbu7a78tyb3hir23nnt10wcy");

                    b.Navigation("createdByUser");

                    b.Navigation("updatedByUser");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.DonarInfluencerMap", b =>
                {
                    b.HasOne("NewPlasmaDonorsAPI.Models.ProfileModel", "InfluencerProfile")
                        .WithMany()
                        .HasForeignKey("influencedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FKc1nras6llm81y4y25yh3ayjyb");

                    b.HasOne("NewPlasmaDonorsAPI.Models.ProfileModel", "Profile")
                        .WithMany()
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FKj9a68x999klndsilsnp5ap77s");

                    b.Navigation("InfluencerProfile");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.MasterData", b =>
                {
                    b.HasOne("NewPlasmaDonorsAPI.Models.UserModel", "createdByUser")
                        .WithMany()
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKjxlsr7j04idi7yb0cjutfoij6");

                    b.HasOne("NewPlasmaDonorsAPI.Models.UserModel", "updatedByUser")
                        .WithMany()
                        .HasForeignKey("updatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK6au4d9c97e31e0p1a5m4hok7e");

                    b.Navigation("createdByUser");

                    b.Navigation("updatedByUser");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.ProfileMdMap", b =>
                {
                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "md")
                        .WithMany()
                        .HasForeignKey("mdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewPlasmaDonorsAPI.Models.ProfileModel", "profile")
                        .WithMany()
                        .HasForeignKey("profileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("md");

                    b.Navigation("profile");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.ProfileModel", b =>
                {
                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "RelshipScore")
                        .WithMany()
                        .HasForeignKey("RelshipScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKbpb7gg85pmbuiri25bmju0hat");

                    b.HasOne("NewPlasmaDonorsAPI.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("address_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK7qb4kty1ih8s2hauc511hxn6n");

                    b.HasOne("NewPlasmaDonorsAPI.Models.UserModel", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKiaff94dptc6thrqcc7lup4f68");

                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "Education")
                        .WithMany()
                        .HasForeignKey("education_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK6dvtxtc424ogal2jtnxdh7c0");

                    b.HasOne("NewPlasmaDonorsAPI.Models.CompanyLocation", "HomeCenterLocation")
                        .WithMany()
                        .HasForeignKey("homeCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK15rkj9sb7mqtyitx20a9n4m");

                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "Language")
                        .WithMany()
                        .HasForeignKey("language_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKrjn1ucsoa08h67xg24ypuqwxw");

                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "Occupation")
                        .WithMany()
                        .HasForeignKey("occupation_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK45nymxuj55tpmnrj2v2cm08vk");

                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "Race")
                        .WithMany()
                        .HasForeignKey("race_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKryh63mrluhx6dv2xhewpn88yk");

                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "Relationship")
                        .WithMany()
                        .HasForeignKey("relationship_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK7h9k3wpqia2jss4yvlbyf94wa");

                    b.HasOne("NewPlasmaDonorsAPI.Models.MasterData", "RelshipReason")
                        .WithMany()
                        .HasForeignKey("relship_reason_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKgrdgwmydu1ovly29y5b5o3xlp");

                    b.HasOne("NewPlasmaDonorsAPI.Models.UserModel", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("updatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKmfmr6vf2ktvwggcqquiumitq7");

                    b.Navigation("Address");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Education");

                    b.Navigation("HomeCenterLocation");

                    b.Navigation("Language");

                    b.Navigation("Occupation");

                    b.Navigation("Race");

                    b.Navigation("Relationship");

                    b.Navigation("RelshipReason");

                    b.Navigation("RelshipScore");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("NewPlasmaDonorsAPI.Models.UserModel", b =>
                {
                    b.HasOne("NewPlasmaDonorsAPI.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("company")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKin8gn4o1hpiwe6qe4ey7ykwq7");

                    b.HasOne("NewPlasmaDonorsAPI.Models.CompanyLocation", "CompanyLocation")
                        .WithMany()
                        .HasForeignKey("companyLocation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKj8wlutnj1on6p9b8m9lhuyylh");

                    b.HasOne("NewPlasmaDonorsAPI.Models.Roles", "RoleNavigation")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FKp56c1712k691lhsyewcssf40f");

                    b.Navigation("Company");

                    b.Navigation("CompanyLocation");

                    b.Navigation("RoleNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
